services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-server
    ports:
      - 9090:9090
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.json:/config.json

  adminer:
    container_name: test-adminer
    hostname: adminer
    image: adminer:5.4.1
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: test-postgres
      ADMINER_DESIGN: dracula
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18
    platform: linux/x86_64
    container_name: test-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: article
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d article"]
      timeout: 5s
      retries: 10
